version: '3'

services:
    main:
        image: anlp.ksaa.gov.sa/lexonomy
        links:
            - camel
            - db
        volumes:
            # - /Users/abbander/dev/lexonomy/website/siteconfig.json:/opt/service/website/siteconfig.json
            - ${LEXO_WEBSITE_PATH}:/opt/service/website
            - ${LEXO_DATA_PATH}:/opt/service/data
        environment:
            - MYSQL_DB_HOST=${MYSQL_DB_HOST}
            - MYSQL_DB_USER=${MYSQL_DB_USER}
            - MYSQL_DB_PASSWORD=${MYSQL_DB_PASSWORD}
            - MYSQL_DB_PORT=${MYSQL_DB_PORT}
            - DEBUG=${DEBUG}
            - CAMEL=http://camel
        ports:
            - "8000:8000"
        entrypoint: /bin/sh entrypoint.sh
        depends_on:
          - camel
          - db
    camel:
        image: anlp.ksaa.gov.sa/camel_tools
        volumes:
            - type: bind
              source: ${CAMEL_DATA_PATH}
              target: /root/.camel_tools/data
            - type: bind
              source: ${CAMEL_PATH}
              target: /opt/service
        environment:
            - CAMEL_PORT=${CAMEL_PORT}
            - FLASK_APP=${FLASK_APP}
            - FLASK_ENV=${FLASK_ENV}
        tty: true
        entrypoint: flask run -h 0.0.0.0 -p ${CAMEL_PORT}
    db:
        image: mariadb
        # restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    adminer:
        image: adminer
        # restart: always
        ports:
            - 8080:8080
        depends_on:
          - db